# Generated by Django 4.1.3 on 2022-11-14 16:37

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_owner_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='token',
            field=models.CharField(default=api.models.setToken, max_length=255),
        ),
    ]
