# Generated by Django 4.1.3 on 2022-11-14 17:37

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_owner_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.FileField(upload_to=api.models.getUploadPath),
        ),
    ]
