# Generated by Django 4.1.3 on 2022-11-14 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_code_course_alter_code_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='course',
        ),
        migrations.AddField(
            model_name='code',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.lesson'),
            preserve_default=False,
        ),
    ]
