# Generated by Django 4.1.3 on 2022-11-15 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('api', '0006_remove_code_course_code_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='sessions.session'),
        ),
    ]
