# Generated by Django 4.1.3 on 2022-11-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_code_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('python', 'python'), ('web frontend', 'web frontend')], max_length=50),
        ),
    ]
